### ISSUE TITLE
stream ended unexpectedly

### ISSUE THREAD

**Issue by parimalsparken** [expressjs/connect-multiparty#21]
When i don't pass any parameter in from data it shows below error

Error: stream ended unexpectedly
    at Form.<anonymous> (C:\xampp\htdocs\school\node_modules\multiparty\index.js:754:24)
    at emitNone (events.js:91:20)
    at Form.emit (events.js:185:7)
    at finishMaybe (_stream_writable.js:512:14)
    at endWritable (_stream_writable.js:522:3)
    at Form.Writable.end (_stream_writable.js:487:5)
    at IncomingMessage.onend (_stream_readable.js:511:10)
    at IncomingMessage.g (events.js:292:16)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)

**Comment by dougwilson** [comment]
I tried to reproduce really quick with an empty form but didn't get that error. Can you help provide instruction on how to reproduce so I can take a look? Provide the following, for example:

1. Version of Node.js
2. Version of this and all other used modules
3. Complete server code I can copy and paste and run to see the issue
4. Instructions on what request (include a copy of the request or code that creates the request) to make to produce the given error.

Thanks!

**Comment by dougwilson** [comment]
Closing due to no response.
