### ISSUE TITLE
File upload from android device to node server 

### ISSUE THREAD

**Issue by yogeshbansal** [expressjs/connect-multiparty#25]
I am trying to upload a file from an Android device using ionic 3 framework to node server. It giving the below error. Same code is working fine from iphone.
```
0|npm      | Dev : Error error { Error: stream ended unexpectedly
0|npm      |     at Form.<anonymous> (/home/ec2-user/application/apiserver-v2/node_modules/connect-multiparty/node_modules/multiparty/index.js:764:24)
0|npm      |     at Form.emit (events.js:187:15)
0|npm      |     at Form.EventEmitter.emit (domain.js:442:20)
0|npm      |     at finishMaybe (_stream_writable.js:654:14)
0|npm      |     at endWritable (_stream_writable.js:662:3)
0|npm      |     at Form.Writable.end (_stream_writable.js:602:5)
0|npm      |     at IncomingMessage.onend (_stream_readable.js:634:10)
0|npm      |     at Object.onceWrapper (events.js:275:13)
0|npm      |     at IncomingMessage.emit (events.js:187:15)
0|npm      |     at IncomingMessage.EventEmitter.emit (domain.js:442:20)
0|npm      |     at endReadableNT (_stream_readable.js:1091:14)
0|npm      |     at process._tickCallback (internal/process/next_tick.js:174:19) status: 400, statusCode: 400 }
```

**Comment by yogeshbansal** [comment]
Hi @dougwilson, I am using the Ionic framework file transfer plugin to upload the image file. Using the same code on iPhone is working fine, but from the Android phone is not working. Could you please let me know, what information, you need from me. I will try to provide you asap.

**Comment by dougwilson** [comment]
Hi @yogeshbansal I'm just looking for you to either (a) make a pull request with a fix or (b) provide a reproduction case I can look into. Thanks!

**Comment by dougwilson** [comment]
Closing due to inactivity.
